### PR TITLE
Release v0.1.6

### PR DESCRIPTION
**Pull request by woky**

### CODE REVIEW

**Review by zsluedem — APPROVED** [review]

**Review by adaszko — APPROVED** [review]

**Comment by zsluedem** [comment]
@woky I think we should release the version now.

**Comment by woky** [comment]
@zsluedem Got it. Merging. Will tag the _bump_ version commit.

**Comment by woky** [comment]
Correction. Will tag the _merge_ commit, this time.

**Comment by woky** [comment]
Uploaded to PyPi.

**Pull request merged**
