### PR TITLE
update pipenv lock file

### PR DESCRIPTION
**Pull request by zsluedem**

### CODE REVIEW

**Comment by zsluedem** [comment]
@woky You forgot to update the lock file.

**Comment by woky** [comment]
@zsluedem Thanks. I noticed in the diff `mypy-protobuf` and some other ones. Shouldn't I also add them to `setup.py` in `extras_require['dev']`?

**Comment by zsluedem** [comment]
wired~! It is my local package. How did I get it there? Let me fix.

**Comment by zsluedem** [comment]
@woky I think it looks OK now.

I was trying https://github.com/dropbox/mypy-protobuf to generate the stub file of the generated python files. That's why it stayed there.

**Comment by woky** [comment]
I think it'd be good to have it as extras dependency if it can type-check the generated Python files. I have little experience with mypy so I haven't ventured into yet. (I think I've ignored everything related to gRPC/protobufs in `mypy.ini`.)

**Pull request merged**
